### PR TITLE
Require network to be up in RPM init script.

### PR DESCRIPTION
**Pull request by mkubenka**
Fix error "Unable to obtain metadata parameters: project_id zone vm_id".

### CODE REVIEW

**Comment by mr-salty** [comment]
Hi - thanks for the PR.  It looks like this is fixed upstream in https://github.com/treasure-data/omnibus-td-agent/commit/70f48f56fa23e4dc7467ac658761be6c74b2c5ea so I will pull that.

While investigating this issue, I noticed that google-fluentd did not start on my machine after a reboot (which is also fixed by the same upstream change), which I must have missed in my testing.  So, I am curious how you discovered this problem, did you manually fix the init scripts to start at boot?

**Comment by mkubenka** [comment]
Ah, cool. I have missed that fix in upstream.

Well, from time to time google-fluentd did not start so I start investigating logs and find out error message:

```
Unable to obtain metadata parameters: project_id zone vm_id
```

Coincidentally, I fixed same issue with my service for sending custom metrics to StackDriver same day. Therefore, it was easy fix.

**Comment by mr-salty** [comment]
Am I correct in thinking you saw this issue after a reboot?  It looks like prior to the upstream change, (which is now merged but not yet released FYI), that google-fluentd would not automatically start after a reboot at all, so I was wondering if you manually fixed that issue?  Or, was your system restarting google-fluentd after a reboot?  Or did you discover the issue in some other way?

With google-fluentd_1.5.0-1 I see this:

```
$   ls /etc/rc.d/*/*google-fluentd
/etc/rc.d/init.d/google-fluentd    /etc/rc.d/rc3.d/K20google-fluentd
/etc/rc.d/rc0.d/K20google-fluentd  /etc/rc.d/rc4.d/K20google-fluentd
/etc/rc.d/rc1.d/K20google-fluentd  /etc/rc.d/rc5.d/K20google-fluentd
/etc/rc.d/rc2.d/K20google-fluentd  /etc/rc.d/rc6.d/K20google-fluentd
```

i.e there are no Start scripts, only Kill.

**Comment by mr-salty** [comment]
I'm going to close this PR, but if you have any comments about the above I'd love to have your feedback.

**Pull request closed without merging**
