### PR TITLE
 Turn on partial_success by default.

### PR DESCRIPTION
**Pull request by qingling128**
Reviving https://github.com/GoogleCloudPlatform/google-fluentd/pull/66. That one got automatically closed when I deleted the `lingshi-windows` branch. (Should have switched base to master first then delete the branch).

### CODE REVIEW

**Comment by igorpeshansky** [comment]
Let's just reopen #66... There's comment history there.

**Comment by qingling128** [comment]
I had tried to open https://github.com/GoogleCloudPlatform/google-fluentd/pull/66 already. unfortunately Github does not allow it because the `lingshi-partial` has been rebased and force pushed.

**Comment by qingling128** [comment]
Tried to follow the workaround [here](https://github.com/isaacs/github/issues/361#issuecomment-219088644) and [there](https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c) to reopen https://github.com/GoogleCloudPlatform/google-fluentd/pull/66. Neither one works. The old sha seems deleted:
```
$ git clone git@github.com:GoogleCloudPlatform/google-fluentd.git && cd google-fluentd
Cloning into 'google-fluentd'...
remote: Counting objects: 3021, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 3021 (delta 14), reused 16 (delta 11), pack-reused 2993
Receiving objects: 100% (3021/3021), 645.45 KiB | 7.42 MiB/s, done.
Resolving deltas: 100% (1461/1461), done.

$ git checkout 035dceb97a0272a345a697e26adfbe0910f21d92
fatal: reference is not a tree: 035dceb97a0272a345a697e26adfbe0910f21d92
```

**Comment by igorpeshansky** [comment]
I think I managed to fix this. One more try.

**Pull request closed without merging**
