### PR TITLE
Upgrade fluentd to v1.13.3 (from v1.11.2).

### PR DESCRIPTION
**Pull request by igorpeshansky**

### CODE REVIEW

**Comment by qingling128** [comment]
Changes like fluentd upgrade has a higher chance of being rolled back. Are the other changes tied to the version upgrade? If not, can we split them into a separate PR?

**Comment by qingling128** [comment]
Waiting for soak tests (b/195345361#comment2) to finish before LGTM.

**Comment by igorpeshansky** [comment]
Yes, this is a draft PR, and I'll likely split it into a feature PR (for local gem support) and a version bump PR.

**Comment by igorpeshansky** [comment]
The local gem support feature was split out into #348. Once that's merged, I'll rebase this one.

**Review by qingling128 — APPROVED** [review]
Soak tests look OK: b/195345361#comment10

**Pull request merged**
