### PR TITLE
Update fluentd to v0.14.14

### PR DESCRIPTION
**Pull request by drobune**
I have tried to use second output but I couldn't.
It seems to need https://github.com/fluent/fluentd/pull/1283.

### CODE REVIEW

**Comment by drobune** [comment]
I signed it!

**Comment by martinheidegger** [comment]
LGTM

**Comment by dhrupadb** [comment]
LGTM. Will merge into master once we've tested the changes.

**Comment by igorpeshansky** [comment]
Why not [v0.14.14?](https://github.com/fluent/fluentd/releases/tag/v0.14.14)?

**Comment by qingling128** [comment]
`v0.14.14` does include some performance improvement that we might care: https://github.com/fluent/fluentd/issues/1485 (Originally reported by Kubernetes).

**Comment by drobune** [comment]
Thank you for comments.
I have't noticed v0.14.14. It looks good.

**Comment by igorpeshansky** [comment]
Oh, this was on the wrong branch?

**Comment by dhrupadb** [comment]
No we needed the changes to be staged on a branch of the repo to run a test build. #25 will merge the changes into master.

**Pull request merged**
